### ISSUE TITLE
feature request : an i18n key manger 

### ISSUE THREAD

**Issue by zakidze** [vordgi/nimpl-i18n#57]
feature request : an i18n key manger  to simplify the prosess of making i18n a dashboard  that generates json dictionries for all your laungauge so you can review your keys

**Comment by vordgi** [comment]
The package cannot predict all valid keys, since it is possible to transfer contexts to the client, for example, the entire home. And from this you cannot generate what keys will be inside home until you add them to json

**Comment by zakidze** [comment]
mybe as seprate  app reads keys example read all english keys and joing them with all german keys (just example)  and export the keys to be later used


or read from a locales folder and modify 


but it would be a standalone app

**Comment by vordgi** [comment]
> do you know a way to pass a variable from any server component to root layout???

No, it can't exist. Layout is assembled separately and is not rerendered, since it is assembled on the server

**Comment by vordgi** [comment]
> mybe as seprate app reads keys example read all english keys and joing them with all german keys (just example) and export the keys to be later used

like:

en.json:
```json
{
  "term1": "translate 1",
  "term2": "translate 2",
  "term3": "translate 3",
}
```


de.json:
```json
{
  "term1": "other translate 1",
}
```

`run some-command -f de.json`


de.json:
```json
{
  "term1": "other translate 1",
  "term2": "translate 2",
  "term3": "translate 3",
}
```

**Comment by zakidze** [comment]
![Capture](https://github.com/vordgi/next-translation/assets/61497110/ccb0a20a-2dbe-4405-a6b8-b5ed7b46baaf)


somthing like this an app with GUI where you open the root folder and it detects the subfolder if they exsist and all jsons ,
you can modify the keys or add , or remove, and it will modify the jsons inside

**Comment by vordgi** [comment]
_Working on it!)_

**Comment by zakidze** [comment]
hope we see it come to life

**Comment by vordgi** [comment]
It still in closed development, but you can try it - https://www.npmjs.com/package/@nimpl/inio

**Comment by zakidze** [comment]
very nice exaclty can i contribute to?? mybe i can help with some stuff also hope it would be open source for everyhone to use and standard for every laungauge

**Comment by vordgi** [comment]
Hope to clean up there within the next week and then open-source it

**Comment by vordgi** [comment]
Open-sourced tool - @nimpl/inio - https://github.com/vordgi/nimpl-inio. You can write there for all further questions and ideas

**Comment by zakidze** [comment]
lets gooooo 🚀🚀🚀🚀🚀
