### ISSUE TITLE
Can't work with robots.ts and sitemap.ts files

### ISSUE THREAD

**Issue by IlhomYuldoshev** [vordgi/nimpl-i18n#99]
Here is my folder structure and whenever I tried to open sitemap or robots path it gives error, how to fix this error

<img width="398" alt="Снимок экрана 2024-08-07 в 09 37 44" src="https://github.com/user-attachments/assets/5139c240-4f5b-4d38-af1b-313c66c0e1b0">

<img width="1440" alt="Снимок экрана 2024-08-07 в 09 38 24" src="https://github.com/user-attachments/assets/95bd35b0-14df-48e4-b1ce-40a42fc8e70b">

**Comment by vordgi** [comment]
Hello!

There's no relation with the package here, only with the peculiarities of route processing in Next.js. Specifically, it processes approximately in the following order:
* Rewrites and redirects;
* Static routes (including sitemap);
* Dynamic routes;

In your case, it reached the dynamic routes and an error throwed up there. To prevent the error from occurring, you should add a check for the locale:

`if (!validLanguages.includes(lang)) return notFound();`

Also, the sitemap file is located at `/sitemap.xml`, and robots at `/robots.txt`
